<?php

use Illuminate\Database\Seeder;
use ZEDx\Models\Language;

class LanguageTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $languages = $this->getLanguages();
        Language::insert($languages);
    }

    protected function getLanguages()
    {
        return [
            ['code' => 'aa', 'name' => 'Afaraf'],
            ['code' => 'ab', 'name' => 'Аҧсуа'],
            ['code' => 'ae', 'name' => 'Avesta'],
            ['code' => 'af', 'name' => 'Afrikaans'],
            ['code' => 'ak', 'name' => 'Akan'],
            ['code' => 'am', 'name' => 'አማርኛ'],
            ['code' => 'an', 'name' => 'Aragonés'],
            ['code' => 'ar', 'name' => 'العربية'],
            ['code' => 'as', 'name' => 'অসমীয়া'],
            ['code' => 'av', 'name' => 'авар мацӀ ; магӀарул мацӀ'],
            ['code' => 'ay', 'name' => 'Aymar aru'],
            ['code' => 'az', 'name' => 'Azərbaycan dili'],
            ['code' => 'ba', 'name' => 'башҡорт теле'],
            ['code' => 'be', 'name' => 'Беларуская'],
            ['code' => 'bg', 'name' => 'български език'],
            ['code' => 'bh', 'name' => 'भोजपुरी'],
            ['code' => 'bi', 'name' => 'Bislama'],
            ['code' => 'bm', 'name' => 'Bamanankan'],
            ['code' => 'bn', 'name' => 'বাংলা'],
            ['code' => 'bo', 'name' => 'བོད་ཡིག'],
            ['code' => 'br', 'name' => 'Brezhoneg'],
            ['code' => 'bs', 'name' => 'Bosanski jezik'],
            ['code' => 'ca', 'name' => 'Català'],
            ['code' => 'ce', 'name' => 'нохчийн мотт'],
            ['code' => 'ch', 'name' => 'Chamoru'],
            ['code' => 'co', 'name' => 'Corsu ; lingua corsa'],
            ['code' => 'cr', 'name' => 'ᓀᐦᐃᔭᐍᐏᐣ'],
            ['code' => 'cs', 'name' => 'Česky ; čeština'],
            ['code' => 'cu', 'name' => 'Словѣньскъ'],
            ['code' => 'cv', 'name' => 'чӑваш чӗлхи'],
            ['code' => 'cy', 'name' => 'Cymraeg'],
            ['code' => 'da', 'name' => 'Dansk'],
            ['code' => 'de', 'name' => 'Deutsch'],
            ['code' => 'dv', 'name' => 'ދިވެހި'],
            ['code' => 'dz', 'name' => 'རྫོང་ཁ'],
            ['code' => 'ee', 'name' => 'Ɛʋɛgbɛ'],
            ['code' => 'el', 'name' => 'Ελληνικά'],
            ['code' => 'en', 'name' => 'English'],
            ['code' => 'eo', 'name' => 'Esperanto'],
            ['code' => 'es', 'name' => 'Español'],
            ['code' => 'et', 'name' => 'Eesti keel'],
            ['code' => 'eu', 'name' => 'Euskara'],
            ['code' => 'fa', 'name' => 'فارسی'],
            ['code' => 'ff', 'name' => 'Fulfulde'],
            ['code' => 'fi', 'name' => 'Suomen kieli'],
            ['code' => 'fj', 'name' => 'Vosa Vakaviti'],
            ['code' => 'fo', 'name' => 'Føroyskt'],
            ['code' => 'fr', 'name' => 'Français'],
            ['code' => 'fy', 'name' => 'Frysk'],
            ['code' => 'ga', 'name' => 'Gaeilge'],
            ['code' => 'gd', 'name' => 'Gàidhlig'],
            ['code' => 'gl', 'name' => 'Galego'],
            ['code' => 'gn', 'name' => 'Avañe\'ẽ'],
            ['code' => 'gu', 'name' => 'ગુજરાતી'],
            ['code' => 'gv', 'name' => 'Ghaelg'],
            ['code' => 'ha', 'name' => 'هَوُسَ'],
            ['code' => 'he', 'name' => 'עברית'],
            ['code' => 'hi', 'name' => 'हिन्दी ; हिंदी'],
            ['code' => 'ho', 'name' => 'Hiri Motu'],
            ['code' => 'hr', 'name' => 'Hrvatski'],
            ['code' => 'ht', 'name' => 'Kreyòl ayisyen'],
            ['code' => 'hu', 'name' => 'magyar'],
            ['code' => 'hy', 'name' => 'Հայերեն'],
            ['code' => 'hz', 'name' => 'Otjiherero'],
            ['code' => 'ia', 'name' => 'Interlingua'],
            ['code' => 'id', 'name' => 'Bahasa Indonesia'],
            ['code' => 'ie', 'name' => 'Interlingue'],
            ['code' => 'ig', 'name' => 'Igbo'],
            ['code' => 'ii', 'name' => 'ꆇꉙ'],
            ['code' => 'ik', 'name' => 'Iñupiaq ; Iñupiatun'],
            ['code' => 'io', 'name' => 'Ido'],
            ['code' => 'is', 'name' => 'Íslenska'],
            ['code' => 'it', 'name' => 'Italiano'],
            ['code' => 'iu', 'name' => 'ᐃᓄᒃᑎᑐᑦ'],
            ['code' => 'ja', 'name' => '日本語 (にほんご)'],
            ['code' => 'jv', 'name' => 'Basa Jawa'],
            ['code' => 'ka', 'name' => 'ქართული'],
            ['code' => 'kg', 'name' => 'KiKongo'],
            ['code' => 'ki', 'name' => 'Gĩkũyũ'],
            ['code' => 'kj', 'name' => 'Kuanyama'],
            ['code' => 'kk', 'name' => 'Қазақ тілі'],
            ['code' => 'kl', 'name' => 'Kalaallisut ; kalaallit oqaasii'],
            ['code' => 'km', 'name' => 'ភាសាខ្មែរ'],
            ['code' => 'kn', 'name' => 'ಕನ್ನಡ'],
            ['code' => 'ko', 'name' => '한국어 (韓國語) ; 조선말 (朝鮮語)'],
            ['code' => 'kr', 'name' => 'Kanuri'],
            ['code' => 'ks', 'name' => 'कश्मीरी ; كشميري'],
            ['code' => 'ku', 'name' => 'Kurdî ; كوردی'],
            ['code' => 'kv', 'name' => 'коми кыв'],
            ['code' => 'kw', 'name' => 'Kernewek'],
            ['code' => 'ky', 'name' => 'кыргыз тили'],
            ['code' => 'la', 'name' => 'Latine ; lingua latina'],
            ['code' => 'lb', 'name' => 'Lëtzebuergesch'],
            ['code' => 'lg', 'name' => 'Luganda'],
            ['code' => 'li', 'name' => 'Limburgs'],
            ['code' => 'ln', 'name' => 'Lingála'],
            ['code' => 'lo', 'name' => 'ພາສາລາວ'],
            ['code' => 'lt', 'name' => 'Lietuvių kalba'],
            ['code' => 'lu', 'name' => 'kiluba'],
            ['code' => 'lv', 'name' => 'Latviešu valoda'],
            ['code' => 'mg', 'name' => 'Fiteny malagasy'],
            ['code' => 'mh', 'name' => 'Kajin M̧ajeļ'],
            ['code' => 'mi', 'name' => 'Te reo Māori'],
            ['code' => 'mk', 'name' => 'македонски јазик'],
            ['code' => 'ml', 'name' => 'മലയാളം'],
            ['code' => 'mn', 'name' => 'Монгол'],
            ['code' => 'mo', 'name' => 'лимба молдовеняскэ'],
            ['code' => 'mr', 'name' => 'मराठी'],
            ['code' => 'ms', 'name' => 'Bahasa Melayu ; بهاس ملايو'],
            ['code' => 'mt', 'name' => 'Malti'],
            ['code' => 'my', 'name' => 'ဗမာစာ'],
            ['code' => 'na', 'name' => 'Ekakairũ Naoero'],
            ['code' => 'nb', 'name' => 'Norsk bokmål'],
            ['code' => 'nd', 'name' => 'isiNdebele'],
            ['code' => 'ne', 'name' => 'नेपाली'],
            ['code' => 'ng', 'name' => 'Owambo'],
            ['code' => 'nl', 'name' => 'Nederlands'],
            ['code' => 'nn', 'name' => 'Norsk nynorsk'],
            ['code' => 'no', 'name' => 'Norsk'],
            ['code' => 'nr', 'name' => 'Ndébélé'],
            ['code' => 'nv', 'name' => 'Diné bizaad ; Dinékʼehǰí'],
            ['code' => 'ny', 'name' => 'ChiCheŵa ; chinyanja'],
            ['code' => 'oc', 'name' => 'Occitan'],
            ['code' => 'oj', 'name' => 'ᐊᓂᔑᓈᐯᒧᐎᓐ'],
            ['code' => 'om', 'name' => 'Afaan Oromoo'],
            ['code' => 'or', 'name' => 'ଓଡ଼ିଆ'],
            ['code' => 'os', 'name' => 'Ирон æвзаг'],
            ['code' => 'pa', 'name' => 'ਪੰਜਾਬੀ ; پنجابی'],
            ['code' => 'pi', 'name' => 'पािऴ'],
            ['code' => 'pl', 'name' => 'Polski'],
            ['code' => 'ps', 'name' => 'پښتو'],
            ['code' => 'pt', 'name' => 'Português'],
            ['code' => 'qu', 'name' => 'Runa Simi ; Kichwa'],
            ['code' => 'rc', 'name' => 'Kréol Rénioné'],
            ['code' => 'rm', 'name' => 'Rumantsch grischun'],
            ['code' => 'rn', 'name' => 'kiRundi'],
            ['code' => 'ro', 'name' => 'Română'],
            ['code' => 'ru', 'name' => 'русский язык'],
            ['code' => 'rw', 'name' => 'Kinyarwanda'],
            ['code' => 'sa', 'name' => 'संस्कृतम्'],
            ['code' => 'sc', 'name' => 'sardu'],
            ['code' => 'sd', 'name' => 'सिन्धी ; ‫سنڌي، سندھی'],
            ['code' => 'se', 'name' => 'Davvisámegiella'],
            ['code' => 'sg', 'name' => 'Yângâ tî sängö'],
            ['code' => 'si', 'name' => 'සිංහල'],
            ['code' => 'sk', 'name' => 'Slovenčina'],
            ['code' => 'sl', 'name' => 'Slovenščina'],
            ['code' => 'sm', 'name' => 'Gagana fa\'a Samoa'],
            ['code' => 'sn', 'name' => 'chiShona'],
            ['code' => 'so', 'name' => 'Soomaaliga ; af Soomaali'],
            ['code' => 'sq', 'name' => 'Shqip'],
            ['code' => 'sr', 'name' => 'српски језик'],
            ['code' => 'ss', 'name' => 'SiSwati'],
            ['code' => 'st', 'name' => 'seSotho'],
            ['code' => 'su', 'name' => 'Basa Sunda'],
            ['code' => 'sv', 'name' => 'Svenska'],
            ['code' => 'sw', 'name' => 'Kiswahili'],
            ['code' => 'ta', 'name' => 'தமிழ்'],
            ['code' => 'te', 'name' => 'తెలుగు'],
            ['code' => 'tg', 'name' => 'тоҷикӣ ; toğikī ; ‫تاجیکی'],
            ['code' => 'th', 'name' => 'ไทย'],
            ['code' => 'ti', 'name' => 'ትግርኛ'],
            ['code' => 'tk', 'name' => 'Türkmen ; Түркмен'],
            ['code' => 'tl', 'name' => 'Tagalog'],
            ['code' => 'tn', 'name' => 'seTswana'],
            ['code' => 'to', 'name' => 'faka Tonga'],
            ['code' => 'tr', 'name' => 'Türkçe'],
            ['code' => 'ts', 'name' => 'xiTsonga'],
            ['code' => 'tt', 'name' => 'татарча ; tatarça ; ‫تاتارچا'],
            ['code' => 'tw', 'name' => 'Twi'],
            ['code' => 'ty', 'name' => 'Reo Mā`ohi'],
            ['code' => 'ug', 'name' => 'Uyƣurqə ; ‫ئۇيغۇرچ'],
            ['code' => 'uk', 'name' => 'українська мова'],
            ['code' => 'ur', 'name' => 'اردو'],
            ['code' => 'uz', 'name' => 'O\'zbek ; Ўзбек ; أۇزبېك'],
            ['code' => 've', 'name' => 'tshiVenḓa'],
            ['code' => 'vi', 'name' => 'Tiếng Việt'],
            ['code' => 'vo', 'name' => 'Volapük'],
            ['code' => 'wa', 'name' => 'Walon'],
            ['code' => 'wo', 'name' => 'Wollof'],
            ['code' => 'xh', 'name' => 'isiXhosa'],
            ['code' => 'yi', 'name' => 'ייִדיש'],
            ['code' => 'yo', 'name' => 'Yorùbá'],
            ['code' => 'za', 'name' => 'Saɯ cueŋƅ ; Saw cuengh'],
            ['code' => 'zh', 'name' => '中文, 汉语, 漢語'],
            ['code' => 'zu', 'name' => 'isiZulu'],
        ];
    }
}
